name: Backend Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ECR_REGISTRY: 916816679759.dkr.ecr.us-east-1.amazonaws.com
      IMAGE_NAME: backend-python

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # 3. Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .

      # 5. Tag Docker image
      - name: Tag Docker image
        run: |
          docker tag $IMAGE_NAME:latest $ECR_REGISTRY/$IMAGE_NAME:latest

      # 6. Push Docker image
      - name: Push Docker image
        run: |
          docker push $ECR_REGISTRY/$IMAGE_NAME:latest