name: Backend Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ECR_REGISTRY: 916816679759.dkr.ecr.us-east-1.amazonaws.com
      IMAGE_NAME: backend-python

    steps:
      # 1. Checkout código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar credenciales AWS (LabRole)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      # 3. Login a ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Definir versión (tag)
      - name: Generate image tag
        run: |
          echo "IMAGE_TAG=v1.${{ github.run_number }}.${GITHUB_SHA::7}" >> $GITHUB_ENV

      # 5. Instalar dependencias y tests
      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          pytest

      # 6. Build imagen Docker
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      # 7. Tag para ECR
      - name: Tag Docker image
        run: |
          docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      # 8. Push a ECR
      - name: Push Docker image
        run: |
          docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      # 9. (Opcional) Tag latest para despliegue fácil
      - name: Tag latest
        run: |
          docker tag $IMAGE_NAME:$IMAGE_TAG $ECR_REGISTRY/$IMAGE_NAME:latest
          docker push $ECR_REGISTRY/$IMAGE_NAME:latest